### ISSUE TITLE
Lifecycle Hook 호출 순서 

### ISSUE THREAD

**Issue by denzels** [studye/angular#7]
![screenshot 2017-02-08 23 48 51](https://cloud.githubusercontent.com/assets/304682/22742202/422c91ac-ee59-11e6-8d76-0ab6988c8436.png)
![screenshot 2017-02-08 23 48 59](https://cloud.githubusercontent.com/assets/304682/22742203/4242fff0-ee59-11e6-9922-8b89ace779c0.png)

**Comment by denzels** [comment]
![screenshot 2017-02-10 00 21 04](https://cloud.githubusercontent.com/assets/304682/22789622/dc72be9e-ef26-11e6-9fb7-ec0a4c7ec4b7.png)

**Comment by jongmoon** [comment]
@denzels 초기화 이후 ngDoCheck 의 호출은 표기된 반면 ngOnChanges 의 호출이 표기되지 않은 이유가 있나요?

**Comment by denzels** [comment]
@jongmoon  
저거 input 값 변경없이 그냥 일반적인 change detection에 의한 호출 순서를 그려놓은거야
ngOnChanges는 Input이 변경되야만 호출되니까~

**Comment by denzels** [comment]
![screenshot 2017-02-15 00 21 04](https://cloud.githubusercontent.com/assets/304682/22935081/b4cb9518-f314-11e6-8bb3-2701c4e91877.png)

![screenshot 2017-02-14 22 42 34](https://cloud.githubusercontent.com/assets/304682/22931181/011ec506-f307-11e6-96ba-13cb5efb2e86.png)
