### ISSUE TITLE
5. Dependency Injection 내용 오류

### ISSUE THREAD

**Issue by grapgrap** [studye/angular#8]
안녕하세요 Angular를 공부하고 있는 학생입니다. 정리해놓으신 위키 잘 보고 있습니다.
다름이 아니라 5. Dependency Injection 중 **ngModule 을 사용해서 Depencency Injection을 하기** 부분에 오류가 있는 것 같아 이슈 남깁니다.

![image](https://cloud.githubusercontent.com/assets/16932142/23156263/97e4d258-f859-11e6-9e91-ff9c0d149aa6.png)

위 사진은 오류가 났다고 생각되는 부분입니다.

`providers: [MyService]` 와 밑에 코드가 동일한 기능을 하려면 
`providers: [ { provide: MyService, useClass: MyService } ] ` 가 되야 하는 것이 아닌가 생각됩니다.

해당 내용과 관련된 [angular 공식 문서](https://angular.io/docs/ts/latest/guide/dependency-injection.html)이고, 아래 사진은 그 중 관련 내용을 발췌한 것 입니다.

![image](https://cloud.githubusercontent.com/assets/16932142/23156382/0ec1e154-f85a-11e6-9d0a-fad0ecc07034.png)

오류가 아니라면 아직 angular 초보자인 저에게 코멘트 주시면 감사하겠습니다.

**Comment by denzels** [comment]
안녕하세요.
적어주신 내용이 맞습니다.  저 부분은 오타입니다.
감사합니다. :)

**Comment by grapgrap** [comment]
그렇군요 앞으로도 좋은 내용 기대하겠습니다 XD
